### PR TITLE
Finished implementing all cmath functions

### PR DESCRIPTION
**Pull request by spfrommer**

### CODE REVIEW

**Comment by lefticus** [comment]
Which compiler are you testing on?

**Comment by lefticus** [comment]
@spfrommer I ask because I have no problem with the ll functions on clang-3.5

**Comment by lefticus** [comment]
I've tested gcc-4.6, clang-3.5, MSVC 2013 (32bit + 64bit) with no problem...

**Comment by spfrommer** [comment]
g++ 4.8.2

It compiles fine (except for a few warnings) but fails at runtime with the following error message for functions that return long long ints:
/home/samuel/repositories/bitbucket/ChaiScript_Extras/tests/math.cpp:71: FAILED:
  CHECK( chai.eval<double>("llround(0.5)") == llround(0.5) )
due to unexpected exception with message:
  Cannot perform boxed_cast

**Comment by spfrommer** [comment]
It also doesn't seem to like the atanh test:
/home/samuel/repositories/bitbucket/ChaiScript_Extras/tests/math.cpp:34: FAILED:
  CHECK( chai.eval<double>("atanh(0.5)") == atanh(0.5) )
with expansion:
  0.5493061443 == 0.5493061443

**Comment by lefticus** [comment]
32bit / 64bit? Which OS?

**Comment by spfrommer** [comment]
64 bit.

**Pull request merged**
